from pathlib import Path


def replace_once(path, old, new, label):
    p = Path(path)
    text = p.read_text(encoding="utf-8")
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"{label}: expected one match, found {count}")
    p.write_text(text.replace(old, new, 1), encoding="utf-8")


def replace_between(path, start, end, new, label):
    p = Path(path)
    text = p.read_text(encoding="utf-8")
    i = text.find(start)
    j = text.find(end, i + len(start))
    if i < 0 or j < 0:
        raise RuntimeError(f"{label}: markers missing")
    p.write_text(text[:i] + new + text[j:], encoding="utf-8")


APP = "src/htail_app/app.py"
replace_between(
    APP,
    "    def _refresh_global_search_results(self) -> None:\n",
    "    def _cycle_global_search_file_filter(self, backwards: bool = False) -> None:\n",
    '''    def _refresh_global_search_results(self) -> None:\n        signature, corpus = self._global_search_corpus_data()\n        key = (\n            self.global_search_buffer,\n            self.global_search_mode,\n            self.global_search_ignore_case,\n            self.global_search_sort,\n            self.global_search_file_filter,\n            signature,\n        )\n        if key == self._global_search_cache_key:\n            return\n        self._global_search_cache_key = key\n        try:\n            page = search_corpus(\n                corpus,\n                self.global_search_buffer,\n                self.global_search_mode,\n                self._global_search_flags(),\n                file_filter=self.global_search_file_filter,\n                sort_mode=self.global_search_sort,\n                limit=GLOBAL_SEARCH_LIMIT,\n            )\n        except Exception as exc:\n            self.global_search_results = []\n            self.global_search_error = f"{type(exc).__name__}: {exc}"\n            self.global_search_truncated = False\n            self.global_search_selected = 0\n            return\n        self.global_search_results = page.results\n        self.global_search_error = page.error\n        self.global_search_truncated = page.truncated\n        if self.global_search_results:\n            self.global_search_selected = min(max(0, self.global_search_selected), len(self.global_search_results) - 1)\n        else:\n            self.global_search_selected = 0\n\n''',
    "global search backend guard",
)
replace_between(
    APP,
    "    def _global_search_lines(self, width: int, height: int) -> List[str]:\n",
    "    def _select_global_search_result(self) -> bool:\n",
    '''    def _global_search_lines(self, width: int, height: int) -> List[str]:\n        self._refresh_global_search_results()\n        if self.global_search_file_filter is None:\n            file_label = "[All files]"\n        elif 0 <= self.global_search_file_filter < len(self.panes):\n            file_label = f"[{self.panes[self.global_search_file_filter].name}]"\n        else:\n            file_label = "[All files]"\n        try:\n            return render_global_search(\n                width,\n                height,\n                query=self.global_search_buffer,\n                mode=self.global_search_mode,\n                mode_labels=(\n                    (SEARCH_SIMPLE, "Simple"),\n                    (SEARCH_REGEX, "Regex"),\n                    (SEARCH_BOOLEAN, "Boolean"),\n                    (SEARCH_FUZZY, "Fuzzy"),\n                ),\n                ignore_case=self.global_search_ignore_case,\n                sort_mode=self.global_search_sort,\n                file_filter_label=file_label,\n                results=self.global_search_results,\n                selected=self.global_search_selected,\n                truncated=self.global_search_truncated,\n                error=self.global_search_error,\n                panes=self.panes,\n                preview_enabled=self.global_search_preview,\n                color=self.color,\n            )\n        except Exception as exc:\n            self.global_search_error = f"{type(exc).__name__}: {exc}"\n            return _panel_lines(\n                "Global search",\n                ["Search rendering error:", self.global_search_error, "", "Esc close"],\n                width,\n                height,\n                self.color,\n            )\n\n''',
    "global search render guard",
)
replace_once(
    APP,
    '''        if self.help_active:\n            if key == "?":\n                self.help_active = False\n                self.dirty = True\n            return False\n''',
    '''        if self.help_active:\n            if key in ("?", "ESC"):\n                self.help_active = False\n                self.dirty = True\n            elif key in ("q", "Q"):\n                return True\n            return False\n''',
    "help Esc",
)
replace_once(
    APP,
    '''        if self.update_confirm_active:\n            if key in ("n", "N", "ESC", "q", "Q"):\n                self.update_confirm_active = False\n                self.set_message("update cancelled")\n            elif key in ("y", "Y") and self.update_release is not None and not self.update_installing:\n''',
    '''        if self.update_confirm_active:\n            if self.update_installing:\n                return False\n            if key in ("n", "N", "ESC", "q", "Q"):\n                self.update_confirm_active = False\n                self.set_message("update cancelled")\n            elif key in ("y", "Y") and self.update_release is not None:\n''',
    "active update lock",
)
replace_once(
    APP,
    '''            if stage.startswith("Downloading"):\n                if current is not None and total and total > 0:\n                    self.update_overall_progress = 0.05 + 0.70 * max(0.0, min(1.0, current / total))\n                else:\n                    self.update_overall_progress = max(self.update_overall_progress, 0.10)\n            elif stage.startswith("Verifying"):\n                self.update_overall_progress = max(self.update_overall_progress, 0.80)\n            elif stage.startswith("Backing up"):\n                self.update_overall_progress = max(self.update_overall_progress, 0.90)\n            elif stage.startswith("Installing") or stage.startswith("Replacing"):\n                self.update_overall_progress = max(self.update_overall_progress, 0.97)\n            else:\n                self.update_overall_progress = max(self.update_overall_progress, 0.02)\n''',
    '''            if stage.startswith("Downloading release"):\n                if current is not None and total and total > 0:\n                    self.update_overall_progress = 0.03 + 0.37 * max(0.0, min(1.0, current / total))\n                else:\n                    self.update_overall_progress = max(self.update_overall_progress, 0.08)\n            elif stage.startswith("Verifying release"):\n                self.update_overall_progress = max(self.update_overall_progress, 0.42)\n            elif stage.startswith("Downloading runtime"):\n                if current is not None and total and total > 0:\n                    self.update_overall_progress = 0.45 + 0.30 * max(0.0, min(1.0, current / total))\n                else:\n                    self.update_overall_progress = max(self.update_overall_progress, 0.50)\n            elif stage.startswith("Verifying runtime"):\n                self.update_overall_progress = max(self.update_overall_progress, 0.77)\n            elif stage.startswith("Unpacking runtime"):\n                if current is not None and total and total > 0:\n                    self.update_overall_progress = 0.80 + 0.14 * max(0.0, min(1.0, current / total))\n                else:\n                    self.update_overall_progress = max(self.update_overall_progress, 0.84)\n            elif stage.startswith("Runtime already"):\n                self.update_overall_progress = max(self.update_overall_progress, 0.94)\n            elif stage.startswith("Backing up"):\n                self.update_overall_progress = max(self.update_overall_progress, 0.96)\n            elif stage.startswith("Installing") or stage.startswith("Replacing"):\n                self.update_overall_progress = max(self.update_overall_progress, 0.98)\n            else:\n                self.update_overall_progress = max(self.update_overall_progress, 0.02)\n''',
    "update progress stages",
)

CORE = "src/htail_app/core.py"
replace_once(CORE, "import urllib.request\n", "import urllib.request\nimport zipfile\nimport io\n", "runtime imports")
replace_once(
    CORE,
    '''class ReleaseInfo:\n    version: str\n    tag: str\n    asset_url: str\n    asset_name: str\n    checksum_url: Optional[str] = None\n    notes: str = ""\n''',
    '''class ReleaseInfo:\n    version: str\n    tag: str\n    asset_url: str\n    asset_name: str\n    checksum_url: Optional[str] = None\n    notes: str = ""\n    runtime_url: Optional[str] = None\n    runtime_checksum_url: Optional[str] = None\n    runtime_abi: Optional[str] = None\n''',
    "ReleaseInfo runtime fields",
)
replace_once(
    CORE,
    "\n\nclass UpdateService:\n",
    '''\n\ndef current_cpython_abi() -> str:\n    return f"cp{sys.version_info.major}{sys.version_info.minor}"\n\n\ndef runtime_cache_dir(runtime_id: str, abi: str) -> Path:\n    root = Path(os.environ.get("XDG_CACHE_HOME", Path.home() / ".cache")) / "htail"\n    return root / "runtime" / runtime_id / abi\n\n\ndef _runtime_id_from_source(source: str) -> Optional[str]:\n    match = re.search(r'^HTAIL_RUNTIME_ID\\s*=\\s*"([0-9a-fA-F]{64})"', source, re.MULTILINE)\n    return match.group(1).lower() if match else None\n\n\ndef _install_runtime_bundle(content: bytes, target: Path, runtime_id: str, abi: str, report) -> None:\n    with zipfile.ZipFile(io.BytesIO(content)) as outer:\n        manifest = json.loads(outer.read("runtime.json").decode("utf-8"))\n        if manifest.get("runtime_id") != runtime_id:\n            raise RuntimeError("runtime bundle id does not match htail core")\n        if manifest.get("abi") != abi:\n            raise RuntimeError(f"runtime bundle ABI {manifest.get('abi')!r} does not match {abi}")\n        payloads = []\n        total = 0\n        for wheel_name in manifest.get("wheels") or []:\n            payload = outer.read("wheels/" + wheel_name)\n            with zipfile.ZipFile(io.BytesIO(payload)) as wheel:\n                total += sum(item.file_size for item in wheel.infolist() if not item.is_dir())\n            payloads.append(payload)\n    target.parent.mkdir(parents=True, exist_ok=True)\n    temp = Path(tempfile.mkdtemp(prefix=f".{abi}-", dir=str(target.parent)))\n    current = 0\n    try:\n        report(f"Unpacking runtime {abi}…", current, total)\n        for payload in payloads:\n            with zipfile.ZipFile(io.BytesIO(payload)) as wheel:\n                for item in wheel.infolist():\n                    if item.is_dir():\n                        continue\n                    destination = (temp / item.filename).resolve()\n                    if temp.resolve() not in destination.parents:\n                        raise RuntimeError(f"unsafe runtime path: {item.filename}")\n                    destination.parent.mkdir(parents=True, exist_ok=True)\n                    with wheel.open(item) as src, destination.open("wb") as dst:\n                        shutil.copyfileobj(src, dst)\n                    mode = (item.external_attr >> 16) & 0o777\n                    if mode:\n                        os.chmod(destination, mode)\n                    current += item.file_size\n                    report(f"Unpacking runtime {abi}…", current, total)\n        try:\n            os.replace(temp, target)\n        except OSError:\n            if not target.is_dir():\n                raise\n    finally:\n        if temp.exists():\n            shutil.rmtree(temp, ignore_errors=True)\n\n\nclass UpdateService:\n''',
    "runtime helpers",
)
replace_once(
    CORE,
    '''        assets = payload.get("assets") or []\n        asset_url: Optional[str] = None\n        checksum_url: Optional[str] = None\n        for asset in assets:\n            name = str(asset.get("name") or "")\n            url = str(asset.get("browser_download_url") or "")\n            if name == self.asset_name and url:\n                asset_url = url\n            elif name in (f"{self.asset_name}.sha256", f"{self.asset_name}.sha256sum") and url:\n                checksum_url = url\n''',
    '''        assets = payload.get("assets") or []\n        asset_url: Optional[str] = None\n        checksum_url: Optional[str] = None\n        runtime_abi = current_cpython_abi()\n        runtime_name = f"htail-runtime-{runtime_abi}.zip"\n        runtime_url: Optional[str] = None\n        runtime_checksum_url: Optional[str] = None\n        for asset in assets:\n            name = str(asset.get("name") or "")\n            url = str(asset.get("browser_download_url") or "")\n            if name == self.asset_name and url:\n                asset_url = url\n            elif name in (f"{self.asset_name}.sha256", f"{self.asset_name}.sha256sum") and url:\n                checksum_url = url\n            elif name == runtime_name and url:\n                runtime_url = url\n            elif name in (f"{runtime_name}.sha256", f"{runtime_name}.sha256sum") and url:\n                runtime_checksum_url = url\n''',
    "runtime asset lookup",
)
replace_once(
    CORE,
    '''            checksum_url=checksum_url,\n            notes=notes,\n        )\n''',
    '''            checksum_url=checksum_url,\n            notes=notes,\n            runtime_url=runtime_url,\n            runtime_checksum_url=runtime_checksum_url,\n            runtime_abi=runtime_abi,\n        )\n''',
    "runtime metadata return",
)
replace_once(CORE, '            report("Verifying SHA-256 checksum…")\n', '            report("Verifying release SHA-256 checksum…")\n', "release verify label")
replace_once(
    CORE,
    '''            try:\n                compile(source, str(target), "exec")\n            except SyntaxError as exc:\n                return False, f"downloaded update failed syntax validation: {exc}"\n\n            report("Preparing update…")\n''',
    '''            try:\n                compile(source, str(target), "exec")\n            except SyntaxError as exc:\n                return False, f"downloaded update failed syntax validation: {exc}"\n\n            runtime_id = _runtime_id_from_source(source)\n            if runtime_id:\n                abi = release.runtime_abi or current_cpython_abi()\n                runtime_target = runtime_cache_dir(runtime_id, abi)\n                if runtime_target.is_dir():\n                    report(f"Runtime already prepared ({abi})…")\n                else:\n                    if not release.runtime_url or not release.runtime_checksum_url:\n                        return False, f"release {release.tag} has no runtime asset for {abi}"\n                    runtime_request = urllib.request.Request(release.runtime_url, headers={"User-Agent": f"htail/{HTAIL_VERSION}"})\n                    with urllib.request.urlopen(runtime_request, timeout=20.0) as response:\n                        headers = getattr(response, "headers", {})\n                        size = headers.get("Content-Length") if hasattr(headers, "get") else None\n                        runtime_total = int(size) if size and size.isdigit() else None\n                        runtime_chunks = []\n                        runtime_current = 0\n                        report(f"Downloading runtime {abi}…", runtime_current, runtime_total)\n                        while True:\n                            try:\n                                chunk = response.read(65536)\n                            except TypeError:\n                                chunk = response.read()\n                            if not chunk:\n                                break\n                            runtime_chunks.append(chunk)\n                            runtime_current += len(chunk)\n                            report(f"Downloading runtime {abi}…", runtime_current, runtime_total)\n                        runtime_content = b"".join(runtime_chunks)\n                    report(f"Verifying runtime {abi}…")\n                    checksum_request = urllib.request.Request(release.runtime_checksum_url, headers={"User-Agent": f"htail/{HTAIL_VERSION}"})\n                    with urllib.request.urlopen(checksum_request, timeout=10.0) as response:\n                        checksum_text = response.read().decode("utf-8", errors="replace")\n                    checksum_match = re.search(r"\\b([0-9a-fA-F]{64})\\b", checksum_text)\n                    if not checksum_match:\n                        return False, "runtime checksum asset does not contain a SHA-256 digest"\n                    if hashlib.sha256(runtime_content).hexdigest() != checksum_match.group(1).lower():\n                        return False, "downloaded runtime failed SHA-256 verification"\n                    _install_runtime_bundle(runtime_content, runtime_target, runtime_id, abi, report)\n\n            report("Preparing update…")\n''',
    "runtime install before restart",
)

replace_once("src/htail_app/__init__.py", 'VERSION = "0.16.0"\n', 'VERSION = "0.16.1"\n', "version")
replace_once(
    "tests/test_bundle.py",
    '''                    str(ROOT / "tools" / "build_release.py"),\n                    "--no-vendor",\n                    "--output",\n''',
    '''                    str(ROOT / "tools" / "build_release.py"),\n                    "--output",\n''',
    "bundle CLI",
)

Path("tests/test_esc_global_0161.py").write_text("""from __future__ import annotations\n\nfrom pathlib import Path\nimport tempfile\nimport unittest\n\nfrom htail_app import app, core\nfrom htail_app.app import MultiApp\nfrom htail_app.input import InputReader, parse_escape_sequence\n\n\nclass EscapeReaderTests(unittest.TestCase):\n    def test_lone_escape_never_performs_blocking_continuation_read(self):\n        reader = InputReader()\n        reader._fd = 123\n        reader._input_ready = lambda timeout: False\n        reader._read_byte = lambda: self.fail('unexpected read')\n        self.assertEqual(parse_escape_sequence(reader._read_escape_sequence(b'\\x1b')), 'ESC')\n\n\nclass ModalEscapeTests(unittest.TestCase):\n    def make_app(self, root, color=False):\n        source = Path(root) / 'coord.md'\n        source.write_text('# Coordination\\nWorkflow verification remains authoritative.\\n', encoding='utf-8')\n        argv = [str(source), '--no-native-watch']\n        if not color:\n            argv.append('--no-color')\n        return MultiApp(app.parse_args(argv), color, core.DisplayFilter(), core.UpdateService(''))\n\n    def test_escape_closes_all_dismissible_modals(self):\n        with tempfile.TemporaryDirectory() as td:\n            a = self.make_app(td)\n            try:\n                a.handle_input(':'); self.assertTrue(a.palette_active); a.handle_input('ESC'); self.assertFalse(a.palette_active)\n                a.handle_input('g'); self.assertTrue(a.global_search_active); a.handle_input('ESC'); self.assertFalse(a.global_search_active)\n                a.handle_input('/'); a.handle_input('ESC'); self.assertIsNone(a.prompt_mode)\n                a.handle_input('h'); a.handle_input('ESC'); self.assertIsNone(a.prompt_mode)\n                a.handle_input('l'); a.handle_input('ESC'); self.assertFalse(a.layout_menu)\n                a.handle_input('?'); a.handle_input('ESC'); self.assertFalse(a.help_active)\n                a.update_confirm_active = True; a.handle_input('ESC'); self.assertFalse(a.update_confirm_active)\n            finally:\n                a.close_native_watch()\n\n    def test_typing_global_search_with_color_cannot_exit_viewer(self):\n        with tempfile.TemporaryDirectory() as td:\n            a = self.make_app(td, color=True)\n            try:\n                a.handle_input('g')\n                a.handle_input('v')\n                self.assertTrue(a.global_search_active)\n                width, frame = a._frame_rows()\n                self.assertGreater(width, 0)\n                self.assertIn('Global search', '\\n'.join(core.strip_ansi(row) for row in frame))\n            finally:\n                a.close_native_watch()\n\n\nif __name__ == '__main__':\n    unittest.main()\n""", encoding="utf-8")
