from pathlib import Path


def replace_once(path: str, old: str, new: str) -> None:
    p = Path(path)
    text = p.read_text(encoding='utf-8')
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f'{path}: expected exactly one match, found {count}: {old[:80]!r}')
    p.write_text(text.replace(old, new, 1), encoding='utf-8')


def append_before(path: str, marker: str, addition: str) -> None:
    replace_once(path, marker, addition + marker)


replace_once('src/htail_app/__init__.py', 'VERSION = "0.8.1"', 'VERSION = "0.8.2"')
replace_once('tests/test_bundle.py', 'htail 0.8.1', 'htail 0.8.2')

replace_once(
    'src/htail_app/core.py',
    '''        change_marker_ansi = visible_prefix_ansi(text, 2)\n        body_text = plain_text[2:]\n''',
    '''        change_marker_ansi = visible_prefix_ansi(text, 2)\n        # visible_prefix_ansi deliberately stops after the requested printable\n        # characters, which means a painted gutter's trailing RESET is not\n        # included. Re-close the gutter style before reusing it on continuation\n        # rows; otherwise cyan/bold leaks into wrapped Markdown text.\n        if ANSI_RE.search(change_marker_ansi) and not change_marker_ansi.endswith(RESET):\n            change_marker_ansi += RESET\n        body_text = plain_text[2:]\n''',
)

replace_once(
    'src/htail_app/watcher.py',
    '''from dataclasses import dataclass\nfrom pathlib import Path\nimport time\nfrom typing import List, Optional, Sequence, Tuple\n''',
    '''from dataclasses import dataclass\nimport difflib\nfrom pathlib import Path\nimport time\nfrom typing import List, Optional, Sequence, Tuple\n''',
)
replace_once(
    'src/htail_app/watcher.py',
    '''class WatchUpdate:\n    update_number: int\n    events: Sequence[Tuple[str, List[str]]]\n    added: int\n    replaced: int\n    deleted: int\n    elapsed: Optional[float]\n    now_monotonic: float\n\n\n@dataclass\nclass WatchNotice:\n''',
    '''class WatchUpdate:\n    update_number: int\n    events: Sequence[Tuple[str, List[str]]]\n    added: int\n    replaced: int\n    deleted: int\n    elapsed: Optional[float]\n    now_monotonic: float\n    current_snapshot: Sequence[str]\n    changed_new_indices: Sequence[int]\n\n\n@dataclass\nclass WatchNotice:\n''',
)
append_before(
    'src/htail_app/watcher.py',
    '''class FileFollower:\n''',
    '''def _changed_new_indices(old: Sequence[str], new: Sequence[str]) -> List[int]:\n    """Return current-snapshot row indexes that were added or replaced.\n\n    This mirrors core.compute_changes()'s position-anchored diff semantics so\n    repetitive coordination files do not align a fresh tail with older blocks.\n    Deletions have no row in the new snapshot and therefore no gutter index.\n    """\n    old_keys = [core._line_identity(line) for line in old]\n    new_keys = [core._line_identity(line) for line in new]\n\n    prefix = 0\n    prefix_limit = min(len(old), len(new))\n    while prefix < prefix_limit and old_keys[prefix] == new_keys[prefix]:\n        prefix += 1\n\n    if prefix == len(old) and len(new) >= len(old):\n        return list(range(prefix, len(new)))\n\n    suffix = 0\n    suffix_limit = min(len(old) - prefix, len(new) - prefix)\n    while (\n        suffix < suffix_limit\n        and old_keys[len(old) - 1 - suffix] == new_keys[len(new) - 1 - suffix]\n    ):\n        suffix += 1\n\n    old_end = len(old) - suffix if suffix else len(old)\n    new_end = len(new) - suffix if suffix else len(new)\n    if suffix == 0:\n        return list(range(prefix, new_end))\n\n    matcher = difflib.SequenceMatcher(\n        a=old_keys[prefix:old_end],\n        b=new_keys[prefix:new_end],\n        autojunk=False,\n    )\n    changed: List[int] = []\n    for tag, _i1, _i2, j1, j2 in matcher.get_opcodes():\n        if tag in ("insert", "replace"):\n            changed.extend(range(prefix + j1, prefix + j2))\n    return changed\n\n\n''',
)
replace_once(
    'src/htail_app/watcher.py',
    '''        events, added, replaced, deleted = core.compute_changes(self.previous, current)\n        self.previous = current\n        self.signature = stable_signature\n''',
    '''        events, added, replaced, deleted = core.compute_changes(self.previous, current)\n        changed_new_indices = _changed_new_indices(self.previous, current)\n        self.previous = current\n        self.signature = stable_signature\n''',
)
replace_once(
    'src/htail_app/watcher.py',
    '''            elapsed=elapsed,\n            now_monotonic=now,\n        )\n''',
    '''            elapsed=elapsed,\n            now_monotonic=now,\n            current_snapshot=current,\n            changed_new_indices=changed_new_indices,\n        )\n''',
)

replace_once(
    'src/htail_app/pane.py',
    '''        self._visual_to_logical: List[int] = []\n        self._pending_anchor_logical: Optional[int] = None\n''',
    '''        self._visual_to_logical: List[int] = []\n        self._pending_anchor_logical: Optional[int] = None\n\n        # Independently retain the current verified file snapshot. History is\n        # still kept in self.lines; this snapshot is used only when the whole\n        # current file fits in the pane after an update.\n        self.snapshot_raw: List[str] = []\n        self.snapshot_changed: set[int] = set()\n        self.prefer_snapshot = False\n''',
)
append_before(
    'src/htail_app/pane.py',
    '''    def add_initial(self, raw_lines: Sequence[str]) -> None:\n''',
    '''    def set_snapshot(\n        self,\n        raw_lines: Sequence[str],\n        changed_indices: Sequence[int] = (),\n        *,\n        prefer: bool = False,\n    ) -> None:\n        self.snapshot_raw = list(raw_lines)\n        self.snapshot_changed = set(changed_indices)\n        if prefer:\n            self.prefer_snapshot = True\n\n    def _snapshot_view_rows(self, width: int, height: int) -> Optional[List[str]]:\n        if not self.prefer_snapshot or not self.snapshot_raw or height <= 0:\n            return None\n\n        indexed = [\n            (index, line)\n            for index, line in enumerate(self.snapshot_raw)\n            if self.display_filter.accepts(line)\n        ]\n        if not indexed or len(indexed) > height:\n            return None\n\n        raw_visible = [line for _, line in indexed]\n        if self.highlighter.enabled:\n            styled = self.highlighter.render_lines(raw_visible)\n        else:\n            styled = [line.rstrip("\\r\\n") for line in raw_visible]\n\n        visual: List[str] = []\n        for (source_index, _), row in zip(indexed, styled):\n            if source_index in self.snapshot_changed:\n                row = core.paint("▌ ", core.BOLD_LIGHT_CYAN, self.color) + row\n            wrapped = core.wrap_ansi(row, width) or [""]\n            visual.extend(wrapped)\n            if len(visual) > height:\n                return None\n\n        return [_pad_ansi(row, width) for row in visual] + [" " * width] * max(0, height - len(visual))\n\n''',
)
replace_once(
    'src/htail_app/pane.py',
    '''        if self.paused:\n            self.set_message("paused")\n        else:\n            self.unseen_updates = 0\n            if self.updates:\n                self._pending_anchor_logical = self.updates[-1].start\n            self.set_message("resumed at freshest update")\n''',
    '''        if self.paused:\n            self.prefer_snapshot = False\n            self.set_message("paused")\n        else:\n            self.unseen_updates = 0\n            if self.updates:\n                self._pending_anchor_logical = self.updates[-1].start\n                self.prefer_snapshot = True\n            self.set_message("resumed at freshest update")\n''',
)
replace_once('src/htail_app/pane.py', '''    def freshest(self) -> None:\n        if self.updates:\n            self._pending_anchor_logical = self.updates[-1].start\n            self.unseen_updates = 0\n''', '''    def freshest(self) -> None:\n        if self.updates:\n            self._pending_anchor_logical = self.updates[-1].start\n            self.unseen_updates = 0\n            self.prefer_snapshot = True\n''')
replace_once('src/htail_app/pane.py', '''    def previous_update(self) -> None:\n        if not self.updates:\n            return\n        current = self._logical_at_top()\n''', '''    def previous_update(self) -> None:\n        if not self.updates:\n            return\n        self.prefer_snapshot = False\n        current = self._logical_at_top()\n''')
replace_once('src/htail_app/pane.py', '''    def next_update(self) -> None:\n        if not self.updates:\n            return\n        current = self._logical_at_top()\n''', '''    def next_update(self) -> None:\n        if not self.updates:\n            return\n        self.prefer_snapshot = False\n        current = self._logical_at_top()\n''')
replace_once('src/htail_app/pane.py', '''        self._pending_anchor_logical = None\n        self._mark_layout_dirty()\n        self.set_message("display cleared; tracking continues")\n''', '''        self._pending_anchor_logical = None\n        self.prefer_snapshot = False\n        self._mark_layout_dirty()\n        self.set_message("display cleared; tracking continues")\n''')
replace_once('src/htail_app/pane.py', '''    def scroll(self, command: str, body_height: int) -> None:\n        if not self._visual_lines:\n            return\n''', '''    def scroll(self, command: str, body_height: int) -> None:\n        if not self._visual_lines:\n            return\n        # Manual scrolling means the user wants the retained history rather\n        # than the automatic short-file snapshot.\n        self.prefer_snapshot = False\n''')
replace_once('src/htail_app/pane.py', '''    def current_update_number(self) -> Optional[int]:\n        current = self._logical_at_top()\n''', '''    def current_update_number(self) -> Optional[int]:\n        if self.prefer_snapshot and self.updates:\n            return self.updates[-1].number\n        current = self._logical_at_top()\n''')
replace_once('src/htail_app/pane.py', '''        remaining = max(0, width - 4 - visible)\n        top_plain = "╭─" + core.strip_ansi(title) + "─" * remaining + "╮"\n''', '''        # Corners + the leading separator consume three cells. The title\n        # is already clipped to width-4, guaranteeing at least one trailing\n        # dash while keeping the top border exactly `width` cells wide.\n        remaining = max(1, width - 3 - visible)\n        top_plain = "╭─" + core.strip_ansi(title) + "─" * remaining + "╮"\n''')
replace_once('src/htail_app/pane.py', '''        body = self.view_rows(inner, body_h)\n        rows = [_pad_ansi(top, width)]\n''', '''        snapshot_body = self._snapshot_view_rows(inner, body_h)\n        body = snapshot_body if snapshot_body is not None else self.view_rows(inner, body_h)\n        rows = [_pad_ansi(top, width)]\n''')

replace_once('src/htail_app/app.py', '''def _dim_line(text: str, color: bool) -> str:\n    if not color or not text.strip():\n        return text\n    return core.DIM + text + core.RESET\n''', '''def _dim_line(text: str, color: bool) -> str:\n    if not color:\n        return text\n    # Embedded syntax-highlight resets cancel SGR 2 (dim). Strip the background\n    # styling first, then apply one uniform dim style so a modal always reads\n    # as foreground over a subdued pane rather than over fully bright colours.\n    plain = core.strip_ansi(text)\n    if not plain.strip():\n        return plain\n    return core.DIM + plain + core.RESET\n''')
replace_once('src/htail_app/app.py', '''            if notice and notice.initial_tail is not None:\n                pane.add_initial(notice.initial_tail)\n                self._stream_initial(len(self.panes), pane, notice.initial_tail)\n''', '''            if notice and notice.initial_tail is not None:\n                pane.add_initial(notice.initial_tail)\n                pane.set_snapshot(follower.previous)\n                self._stream_initial(len(self.panes), pane, notice.initial_tail)\n''')
replace_once('src/htail_app/app.py', '''    def handle_mouse(self, event: MouseEvent) -> None:\n        target = self._pane_at(event.x, event.y)\n        if target is None:\n            return\n        if target >= 0:\n            self.focus = target\n            pane = self.panes[target]\n        else:\n            pane = self.stream\n        if event.button == "left" and event.pressed:\n            self.dirty = True\n            return\n        if event.button in ("wheel_up", "wheel_down"):\n            rect = next((r for i, r in self.last_rects if i == target), None)\n            body_h = max(1, (rect.height - 2) if rect else 5)\n            for _ in range(3):\n                pane.scroll("UP" if event.button == "wheel_up" else "DOWN", body_h)\n            self.dirty = True\n''', '''    def handle_mouse(self, event: MouseEvent) -> None:\n        # SGR mouse mode emits a release event after a click. Never let that\n        # release move focus: its coordinates can be in a different pane if\n        # the pointer moved after the press, which made focus appear to jump\n        # back or require a second click.\n        if event.button == "left" and not event.pressed:\n            return\n\n        target = self._pane_at(event.x, event.y)\n        if target is None:\n            return\n        if target >= 0:\n            self.focus = target\n            pane = self.panes[target]\n        else:\n            pane = self.stream\n        if event.button == "left":\n            self.dirty = True\n            return\n        if event.button in ("wheel_up", "wheel_down"):\n            rect = next((r for i, r in self.last_rects if i == target), None)\n            body_h = max(1, (rect.height - 2) if rect else 5)\n            for _ in range(3):\n                pane.scroll("UP" if event.button == "wheel_up" else "DOWN", body_h)\n            self.dirty = True\n''')
replace_once('src/htail_app/app.py', '''                if result.kind in ("initial", "resumed") and result.initial_tail is not None:\n                    pane.add_initial(result.initial_tail)\n                    self._stream_initial(index, pane, result.initial_tail)\n''', '''                if result.kind in ("initial", "resumed") and result.initial_tail is not None:\n                    pane.add_initial(result.initial_tail)\n                    pane.set_snapshot(follower.previous)\n                    self._stream_initial(index, pane, result.initial_tail)\n''')
replace_once('src/htail_app/app.py', '''                self.stream.add_source_update(index, pane.name, header, rendered, result.now_monotonic)\n                self.dirty = True\n''', '''                pane.set_snapshot(\n                    result.current_snapshot,\n                    result.changed_new_indices,\n                    prefer=not pane.paused,\n                )\n                self.stream.add_source_update(index, pane.name, header, rendered, result.now_monotonic)\n                self.dirty = True\n''')
replace_once('src/htail_app/app.py', '''            while True:\n                event = reader.poll()\n                if event is not None and app.handle_input(event):\n                    break\n                now = time.monotonic()\n''', '''            while True:\n                # Drain a bounded burst of queued terminal input before the\n                # watcher/render pass. A 100 ms file poll interval should not\n                # collapse three quick arrow presses into one sluggish step.\n                quit_requested = False\n                for _ in range(64):\n                    event = reader.poll()\n                    if event is None:\n                        break\n                    if app.handle_input(event):\n                        quit_requested = True\n                        break\n                if quit_requested:\n                    break\n                now = time.monotonic()\n''')

append_before('tests/test_htail.py', '''\n\nclass DiffTests(unittest.TestCase):\n''', '''\n    def test_colored_change_gutter_does_not_leak_into_wrapped_text(self):\n        gutter = htail.paint("▌ ", htail.BOLD_LIGHT_CYAN, True)\n        rows = htail.wrap_ansi(gutter + "plain words that wrap onto another visual row without inheriting cyan", 28)\n        self.assertGreater(len(rows), 1)\n        for row in rows[1:]:\n            prefix_end = row.find(" ") + 1\n            self.assertIn(htail.RESET, row[: max(prefix_end + len(htail.RESET), 1)])\n\n''')
append_before('tests/test_multifile.py', '''\n\nif __name__ == "__main__":\n''', '''\n    def test_update_carries_current_snapshot_and_changed_indexes(self):\n        with tempfile.TemporaryDirectory() as tmp:\n            path = Path(tmp) / "short.log"\n            path.write_text("one\\ntwo\\nthree\\n", encoding="utf-8")\n            follower = FileFollower(path, self.args())\n            follower.initialize_if_available()\n            path.write_text("one\\ntwo\\nTHREE\\n", encoding="utf-8")\n            now = time.monotonic()\n            self.assertIsNone(follower.poll(now))\n            update = follower.poll(now + 0.001)\n            self.assertEqual(list(update.current_snapshot), ["one\\n", "two\\n", "THREE\\n"])\n            self.assertEqual(list(update.changed_new_indices), [2])\n\n''')
append_before('tests/test_panes.py', '''\n\nclass MultiAppInteractionTests(unittest.TestCase):\n''', '''\n    def test_short_snapshot_shows_whole_file_and_marks_changed_row(self):\n        pane = self.make_pane(Path("short.md"))\n        pane.add_initial(["old tail\\n"])\n        pane.add_update(1, [("replace", ["changed\\n"])], 0, 1, 1, None, False, False, 10.0)\n        pane.set_snapshot(["first\\n", "second\\n", "changed\\n"], [2], prefer=True)\n        body = pane._snapshot_view_rows(40, 6)\n        plain = [core.strip_ansi(row).rstrip() for row in body]\n        self.assertEqual(plain[:3], ["first", "second", "▌ changed"])\n\n    def test_pane_top_border_closes_at_exact_right_edge(self):\n        pane = self.make_pane(Path("a.md"))\n        pane.add_initial(["hello\\n"])\n        rows = pane.render_box(40, 8, True, 0)\n        visible = [core.strip_ansi(row) for row in rows]\n        self.assertTrue(all(len(row) == 40 for row in visible))\n        self.assertTrue(visible[0].endswith("╮"))\n        self.assertTrue(visible[1].endswith("│"))\n\n''')
append_before('tests/test_panes.py', '''\n\nif __name__ == "__main__":\n''', '''\n    def test_mouse_release_does_not_change_focus(self):\n        with tempfile.TemporaryDirectory() as tmp:\n            a = Path(tmp) / "a.md"; b = Path(tmp) / "b.md"\n            a.write_text("a\\n", encoding="utf-8"); b.write_text("b\\n", encoding="utf-8")\n            args = parse_args([str(a), str(b), "--layout", "columns", "--no-color", "--no-self-install-prompt"])\n            filt = core.compile_display_filter(args)\n            app = MultiApp(args, False, filt, core.UpdateService("example/repo"))\n            app._pane_boxes(100, 20)\n            app.handle_input(MouseEvent(x=75, y=5, button="left", pressed=True))\n            self.assertEqual(app.focus, 1)\n            app.handle_input(MouseEvent(x=10, y=5, button="left", pressed=False))\n            self.assertEqual(app.focus, 1)\n\n''')
append_before('tests/test_modal_ui.py', '''\n\nif __name__ == "__main__":\n''', '''\n    def test_dim_line_neutralizes_embedded_bright_styles(self):\n        bright = core.paint("bright background", core.BOLD_LIGHT_CYAN, True)\n        dimmed = app._dim_line(bright, True)\n        self.assertIn(core.DIM, dimmed)\n        self.assertNotIn(core.BOLD_LIGHT_CYAN, dimmed)\n        self.assertEqual(core.strip_ansi(dimmed), "bright background")\n\n''')

Path('RELEASE_NOTES.md').write_text('''# htail 0.8.2\n\n## New features\n\n- When an updated file fits completely inside its pane, htail now shows the full current file and marks the changed rows with the cyan change gutter instead of showing only the changed fragment. Manual scrolling or update navigation still opens the retained update history.\n\n## Bug fixes\n\n- Mouse focus now reacts only to the button press, so the release event cannot move focus to whichever pane the pointer reached afterward.\n- Queued keyboard and mouse events are drained in one UI frame, making repeated arrow-key scrolling and fast pane clicks responsive instead of advancing roughly once per watcher poll.\n- Fixed ANSI state leakage from wrapped cyan change gutters that could turn apparently random Markdown continuation text cyan/bold.\n- Modal backgrounds now reliably dim even when the underlying pane contains syntax-highlight ANSI resets.\n- Fixed pane top-border width calculation so the top-right corner joins the right border without a one-cell gap.\n''', encoding='utf-8')

Path('tools/apply_082.py').unlink(missing_ok=True)
Path('.github/workflows/apply-082.yml').unlink(missing_ok=True)
